CV/Models/Education.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CV.Models
{
    public class Education
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string Name { get; set; }
        public string Institution { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime StopDate { get; set; }
    }
}

CV/Models/Experience.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CV.Models
{
    public class Experience
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string Position { get; set; }
        public string Company { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime StopDate { get; set; }
        public string ImageURL { get; set; }
    }
}

CV/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CV.Models
{
    public class Project
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string Name { get; set; }
        public string Description { get; set; }
        public string GitHubLink { get; set; }
        public string Logo { get; set; }
        ///public List<string> ImageLink { get; set; } = new List<string>();

        public List<Project> GetProjects()
        {
            List<string> y = new List<string>();
                y.AddRange(new string[] { "seven", "eight", "nine" });
            List<Project> x = new List<Project>()
            {
                new Project{ Name = "Sistema de lavado Lújan21", Description = "Desarrollado en Visual Basic para un parqueo público situado en San Pedro, CR. Programado en C# bajo una arquitectura de 3 capas conectado a una base de datos local desarrollada en SQL-Server.", GitHubLink = "", Logo = "/Pictures/logoLugan21.png"},
                new Project{ Name = "Shopping Car", Description = "Programado en ASP.NET con C#, bajo una arquitectura de 3 capas (ACCESO A DATOS, NEGOCIO Y UI) y conectada a una base de datos MS-SQLSERVER mediante Entity Framework.", GitHubLink = "", Logo = "/Pictures/ShoppingCarLogo.png" },
                new Project{ Name = "Sistema de gestión CNM", Description = "Software hecho para el Centro Nacional de la Música, programado en C# MVC5, conectado a una base de datos SQL-Server 2016 con el uso de ADO.Net Framework y Ajax para la inserción y peticiones a la base de datos", GitHubLink = "", Logo = "/Pictures/CNMLogo.png" }
            };

            return x;
        }
    }
}

CV/Controllers/EducationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CV.Controllers
{
    public class EducationController : Controller
    {
        // GET: Education
        public ActionResult Index()
        {
            return View();
        }
    }
}

CV/Controllers/ExperienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CV.Controllers
{
    public class ExperienceController : Controller
    {
        // GET: Experience
        public ActionResult Index()
        {
            return View();
        }
    }
}

CV/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CV.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Studies()
        {
            ViewBag.Message = "Estudios llevados.";

            return View();
        }
        public ActionResult Proyects()
        {
            ViewBag.Message = "Proyectos realizados.";

            return View();
        }

        public ActionResult Experience()
        {
            ViewBag.Message = "Experiencia laboral.";

            return View();
        }
       
    }
}

CV/Controllers/ProjectController.cs
using CV.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CV.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project
        public ActionResult Index(Project project)
        {
            List<Project> listaProjectos = project.GetProjects();
            return View(listaProjectos);
        }
    }
}

CV/Views/Home/Experience.cshtml
@{
    ViewBag.Title = "Experiencia";
}
<br />
<h3>@ViewBag.Message</h3>
<br />
<div class="jumbotron fondo textogeneral">
    <div class="row" style="margin:auto">
        <div class="col-md-10 ">
            <p><b>De 23/10/2017 a 10/03/2018 </b>(San Pedro – San José)</p>
            <p><b>Sykes Latin America, </b>Sector: Customer service and sales.</p>
            <p><b>Cargo ocupado: </b>Customer representative for AT&T.</p>
        </div>
        <div class="col-md-2 ">
            <img src="~/Pictures/sykes-logo-sqblue.png " class="img-responsive img-thumbnail"/>
        </div>
        
    </div>
    <hr />
    <div class="row" style="margin:auto">
        <div class="col-md-10 ">
            <p><b>De 15/01/2018 a 23/04/2018 </b>(San Pedro – San José)</p>
            <p><b>Parqueo público Barrio Luján21, </b>Sector: Desarrollo de software.</p>
            <p><b>Cargo ocupado: </b>Programador para un sistema de gestión empresarial.</p>
        </div>
        <div class="col-md-2 ">
            <img src="~/Pictures/logoLugan21.png" class="img-responsive img-thumbnail" />
        </div>
    </div>
    <hr /> <!--Sonos-->
    <div class="row" style="margin:auto">
        <div class="col-md-10 ">
            <p><b>De 01/10/2018 a 109/03/2019 </b>(La Aurora – Heredia)</p>
            <p><b>Sonos, </b>Sector: Soporte Técnico.</p>
            <p><b>Cargo ocupado: </b>Technical Support Specialist.</p>
        </div>
        <div class="col-md-2 ">
            <img src="~/Pictures/Sonos.jpg" class="img-responsive img-thumbnail" />
        </div>
    </div>
    <hr /> <!--Sonos SME-->
    <div class="row" style="margin:auto">
        <div class="col-md-10 ">
            <p><b>De 10/03/2019 a 03/11/2019 </b>(La Aurora – Heredia)</p>
            <p><b>Sonos, </b>Sector: Soporte Técnico.</p>
            <p><b>Cargo ocupado: </b>Subject Matter Expert (SME).</p>
        </div>
        <div class="col-md-2 ">
            <img src="~/Pictures/Sonos.jpg" class="img-responsive img-thumbnail" />
        </div>
    </div>
    <hr /> <!--Splunk-->
    <div class="row" style="margin:auto">
        <div class="col-md-10 ">
            <p><b>De 04/11/2019 a la actualidad </b>(La Aurora – Heredia)</p>
            <p><b>Sonos, </b>Sector: Soporte Técnico.</p>
            <p><b>Cargo ocupado: </b>Splunk Engineer.</p>
        </div>
        <div class="col-md-2 ">
            <img src="~/Pictures/splunk.png" class="img-responsive img-thumbnail" />
        </div>
    </div>
</div>

CV/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicio";
}

<div class="jumbotron textogeneral">
    <div class="row">
        <div class="col-lg-3">
            <img src="~/Pictures/profile.jpg"  class="img-responsive img-rounded" />
        </div>
        <div class="col-lg-9 " >
            <h2>Didier Irias Méndez</h2>
            <p class="lead ">Graduado en el grado de bachiller en Ingeniería Informática, con conocimientos Básicos-Intermedios en Microsoft .NET, Python, diseño web (HTML5, CSS, PHP, JS), Android y Linux entre otros, no veo la programación como algo difícil o estresante, me gusta programar y lo veo como una oportunidad para crear algo totalmente nuevo para ser usado con el fin de mejorar y muchas veces optimizar la manera en que vivimos hoy en día.</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-7">
        <div class="animated ">
            <h2>Información Personal</h2>
            <br />
            <p><b>Edad: </b>22 años.</p>
            <p><b>Teléfono: </b>+506 8592-2222</p>
            <p><b>Nacionalidad: </b>Costarricense</p>
            <p><b>Email: </b>didier.irias@gmail.com</p>
            <p><b>Cuidad de origen: </b>Uvita de Ceiba, Orotina</p>
            <p><b>Residencia actual: </b>La Aurora, Heredia, Costa Rica.</p>
        </div>
    </div>
    <div class="col-md-5">
        <h2>Nociones en: </h2>
        <br />
        <p><b>BI: </b>(Crystal Reports, Report Viewer, qlikSense, Splunk).</p>
        <p><b>.NET: </b>(C#, VB, XAMARIN, MVC5, WebForms, Entity Framework).</p>
        <p><b>Python: </b>(pyCharm).</p>
        <p><b>Desarrollo web: </b>(HTML5, CSS3, JS, PHP, AJAX).</p>
        <p><b>Bases de datos: </b>(mySQL, MS SQL-SERVER, ORACLE).</p>
        <p><b>Control de versiones: </b>(github).</p>
        <p><b>Metodologias agiles: </b>(Scrum).</p>
        <p><b>Ciclo de vida del desarrollo de software: </b></p>
    </div>
</div>
<div class="row">
    <div class="col-md-7">
        <h2>Habilidades blandas</h2>
        <br />
        <p><b>- </b>Bilingüe.</p>
        <p><b>- </b>Proactivo.</p>
        <p><b>- </b>Trabajo en equipo.</p>
        <p><b>- </b>Capacidad de investigación.</p>
        <p><b>- </b>Creación de algoritmos.</p>
        <p><b>- </b>Mejora continua.</p>
        <p><b>- </b>Trabajo bajo presión, responsable, puntual y organizado.</p>
        <p><b>- </b>Desarrollo de personas.</p>
    </div>
    <div class="col-md-5">
        <h2>Programas manejados</h2>
        <br />
        <p><b>* </b>WAMP.</p>
        <p><b>* </b>MS Office.</p>
        <p><b>* </b>sqlDeveloper.</p>
        <p><b>* </b>Packet Tracer.</p>
        <p><b>* </b>Android studio.</p>
        <p><b>* </b>Visual Studio 2015 - 2017.</p>
        <p><b>* </b>SQL-Server management studio.</p>
    </div>
</div>

CV/Views/Home/Studies.cshtml

@{
    ViewBag.Title = "Estudios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h3>@ViewBag.Message</h3>
<br />
<div class="jumbotron fondo textogeneral">
    <div class="row" style="margin:auto">
        <div class="col-md-10 ">
            <p><b>Del 2010 a 2014 </b>(Labrador de San Mateo, Orotina)</p>
            <p><b>Titulo: </b>Bachiller en Educación media.</p>
            <p><b>Institución: </b>Liceo Rural de Labrador.</p>
        </div>
        <div class="col-md-2 ">
            <img src="~/Pictures/LABRADOR LOGO.jpg" class="img-responsive img-thumbnail" />
        </div>

    </div>
    <hr />
    <div class="row" style="margin:auto">
        <div class="col-md-10 ">
            <p><b>Del 2014 a 2016 </b>(Villa los reyes, Orotina)</p>
            <p><b>Titulo: </b>Ingles Conversacional.</p>
            <p><b>Institución: </b>Centro Cultural de Idiomas.</p>
        </div>
        <div class="col-md-2 ">
            <img src="~/Pictures/CENTRO CULTURAL DE IDIOMAS LOGO .jpg" class="img-responsive img-thumbnail" />
        </div>
    </div>
    <hr />
    <div class="row" style="margin:auto">
        <div class="col-md-10 ">
            <p><b>Del 2015 a la actualidad </b>(Tibás, San José)</p>
            <p><b>Titulo: </b>Bachiller en Ingeniería Informática.</p>
            <p><b>Institución: </b>Universidad Hispanoamericana.</p>
        </div>
        <div class="col-md-2 ">
            <img src="~/Pictures/Logo-UH.jpg" class="img-responsive img-thumbnail" />
        </div>
    </div>
</div>



CV/Views/Project/Index.cshtml
@model IEnumerable<CV.Models.Project>
@{
    ViewBag.Title = "Proyectos";
}
    <div >
        <div>
            <div class="">
                <br />
                <h3>@ViewBag.Message</h3>
                <br />
                @{int n = 0; string myFunc = "myFunc";}
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-md-4">
                        <ul class="thumbnails">
                            <li class="span4 text-center" style="list-style:none;">
                                <div class="thumbnail">
                                    <img src="@Html.DisplayFor(x => item.Logo)" alt="">
                                    <h3>@Html.DisplayFor(x => item.Name)</h3>
                                    <p>@Html.DisplayFor(x => item.Description)</p>
                                </div>
                            </li>
                        </ul>

                    </div>
                }
                <!--
    <div class="row">
        <div class="col-md-4 text-center" ng-controller="myCtrl0" ng-app="app0">
            <div class="btn-group">
                <button ng-click="func0()" class="btn">Imagenes</button>
                <img class="btn" src="~/Pictures/if_logo-github_298818.png" />
            </div>
            <div ng-show="showMe0">
                <h1>Menu:</h1>
                <div>Pizza</div>
            </div>
        </div>
        <div class="col-md-4 text-center" ng-controller="myCtrl1" ng-app="app1">
            <div class="btn-group">
                <button ng-click="func1()" class="btn">Imagenes</button>
                <img class="btn" src="~/Pictures/if_logo-github_298818.png" />
            </div>
            <div ng-show="showMe1">
                <h1>Menu:</h1>
                <div>Pizza</div>
            </div>
        </div>
    </div>-->

            </div>
                </div>
        </div>
    </div>







CV/Views/Project/_PartialLujan21.cshtml
<p>Partial view Luján21</p>

CV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="Didier, Irias, Méndez, Didier Irias, Didier Méndez, Didier Irias Méndez, programador, Ingeniero de software" />
    <meta name="description" content="Didier Irias Méndez, desarrollador de software, apasionado por la tecnología." />
    <meta name="author" content="Didier Irias Méndez" />
    <!--slide-->
    <link rel="stylesheet" href="~/Content/animate.css">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
    <title>@ViewBag.Title - Didier Irias Méndez</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Portafolio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Estudios", "Studies", "Home")</li>
                    <li>@Html.ActionLink("Proyectos", "Index", "Project")</li>
                    <li>@Html.ActionLink("Experiencia laboral", "Experience", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Didier Irias Méndez</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        var app0 = angular.module('app0', []);
        app0.controller('myCtrl0', function ($scope) {
            $scope.showMe0 = false;
            $scope.func0 = function () {
                $scope.showMe0 = !$scope.showMe0;
            }
        });

        var app = angular.module('app1', []);
        app.controller('myCtrl1', function ($scope) {
            $scope.showMe1 = false;
            $scope.func1 = function () {
                $scope.showMe1 = !$scope.showMe1;
            }
        });
    </script>
</body>
</html>